#!/bin/sh
#
# netplug - policy agent for netplugd
#
# Copyright 2003 Key Research, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.  You are forbidden from
# redistributing or modifying it under the terms of any other license,
# including other versions of the GNU General Public License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/share/blib/bin
export PATH

exec >> /tmp/netplug.out 2>&1
source /usr/share/blib/etc/bash_env.sh

  link="$1"
action="$2"

case "$action" in
in|out|probe)
    btool --debug nal handle-netplug-event --link=${link} --event=${action}
    ;;
*)
    echo "I have been called with a funny action of \"${action}\"!" 1>&2
    exit 1
    ;;
esac
